project_id = "gigjjgxntulqxmbqxcpe"

[functions.create-faucetpay-deposit]
verify_jwt = false

[functions.faucetpay]
verify_jwt = true

[functions.validate-fingerprint]
verify_jwt = true

[functions.verify-deposit]
verify_jwt = true

[functions.faucetpay-ipn]
verify_jwt = false

[functions.notify-admin-deposit]
verify_jwt = true

[functions.shortlink-callback]
verify_jwt = true

[functions.expire-deposits]
verify_jwt = false

[functions.send-deposit-email]
verify_jwt = false
